### ISSUE TITLE
Initial Public Release Checklist

### ISSUE THREAD

**Issue by ben-marshall** [scarv/xcrypto#44]
Checklist for first public release of XCrypto

**Repository Admin:**
- [x] Pick a license (MIT)
- [x] Pick a version number (0.9.0)
- [x] Repository rename: `hw-crypto-cop` -> `xcrypto`
- [x] Rename environment variables `COP_` -> `XC_`
- [x] Create a `release` tag to pinpoint the initial public release
  - [x] Attach copies of the documentation as PDFs to the release tag.
  - [x] Add some release notes documenting what features are (not) present.
  - [x] See [draft release notice](https://github.com/scarv/hw-crypto-cop/releases)
- [x] Make sure README is up to date.
- [x] Clean up (i.e., remove) unnecessary branches
- [x] Make repository public (and/or reboot)

**Documentation:**
- [x] Specification document proof read
  - [x] make sure commented-out encodings are valid and included
  - [x] solve encoding table in appendix
  - [x] remove changelog
  - [x] residual changes for ld.bu -> ld.b etc.
  - [x] immediate distance fields for xc.psrl.i and xc.psll.i, cshamt => pshamt ?
  - [x] address any remaining marked TODOs
- [x] Implementation document proof read

**RTL:**
- [x] #45 Stop un-implemented AES instructions from hanging the cop. Treat as NOP for now.

**Verification:**
- [x] All BMC proofs passing / explained.

**Open Issues:**
- [x] Issue #28 closed / fixed (scatter/gather data checks)
- [x] Issue #42 closed (final renaming pass)
- [x] Issue #46 closed (residual inconsistencies with names and fields)
