### ISSUE TITLE
RWC Publicised Release Checklist

### ISSUE THREAD

**Issue by ben-marshall** [scarv/xcrypto#62]
A checklist of issues and tasks which need resolving before our next publicised release checkpoint in time for Real World Crypto (RWC) on *09/01/2019*.

**Repository Admin:**
- [ ] Bump Version Numbers
- [ ] Create release tag
  - [ ] Release notes

**Documentation:**
- [ ] Bump document version numbers

**RTL:**
- [ ] #52 `xc.sbox` instruction proposal experiments
- [ ] #56 `xc.sha3.ind` instruction proposal experiments

**Verification:**
- No known issues

**Open Issues:**
- [ ] #17 Example `riscv`/`riscv+xcrypto` instruction sequences in spec.

**Example Code:**
- [ ] Prince block cipher example
- [ ] AES example code
- [ ] #17 "Example code demonstrations"
